name: Issue Reply Demo
run-name: ${{ github.actor }} is testing out github actions.
on:
  issues:
    types: [labeled]
jobs:
  issue-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'help wanted'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 @${{ github.event.issue.user.login }}，我们完全同意你的提议/反馈，欢迎PR。
