name: Issue Reply Demo
run-name: ${{ github.actor }} is testing out github actions.
on:
  issues:
    types: [opened, edited, labeled, unlabeled]
jobs:
  reply-helper:
    runs-on: ubuntu-latest
    env:
      ISSUE: ${{ github.event.issue.body }}
    if: github.event.label.name == 'decrypt_request'
    steps:
      - uses: actions/checkout@main
      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: cache node
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${runner.OS}
      - name: issue body check
        id: issue_verify
        env:
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          npm i dotenv
          touch ./.private_key
          echo "$TEST_PRIVATE_KEY" >> ./.private_key
          touch ./.aes_encrypted_txt
          echo "$ISSUE_BODY" >> ./.aes_encrypted_txt
          echo "$ISSUE_BODY"
          touch .env
          echo HELLO_PRIVATE_KEY=HelloWorld >> .env
          decryptText=$(node ./action_script/text_decrypt.js)
          echo "decryptText=$decryptText" >> $GITHUB_ENV
      - name: reply to issues
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 @${{ github.event.issue.user.login }} ，${{ env.decryptText }}测试完毕，欢迎PR。
